version: "3.9"
services:
    # PHP-FPM Service
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile

    # NGINX Service
    nginx:
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        volumes:
            # Mountlocal 'app' directory to the Nginx root
            - .:/var/www/hazon
        ports:
            - "8080:80"
        depends_on:
            - php-fpm # Depends on the PHP-FPM service
